#!/bin/bash

# . ../.venv/bin/activate

# west build -b nrf52840dongle/nrf52840/bare \
#     samples/subsys/mgmt/mcumgr/smp_svr \
#     --sysbuild \
#     -- \
#     -DEXTRA_CONF_FILE="cdc.conf;fs.conf;shell.conf;shell-mgmt.conf" \
#     -DEXTRA_DTC_OVERLAY_FILE="usb.overlay" \
#     -DCONFIG_MCUMGR_GRP_OS_MCUMGR_PARAMS=y \
#     -DCONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=4096 \
#     -DCONFIG_MCUMGR_TRANSPORT_WORKQUEUE_STACK_SIZE=8192 \
#     -DCONFIG_SHELL_BACKEND_DUMMY_BUF_SIZE=4096 \
#     -DCONFIG_LOG=n

# WORKS:
# west build -b nrf52840dongle/nrf52840/bare \
#     samples/subsys/mgmt/mcumgr/smp_svr \
#     --sysbuild \
#     -- \
#     -DEXTRA_CONF_FILE="cdc.conf;fs.conf;shell.conf;shell-mgmt.conf" \
#     -DEXTRA_DTC_OVERLAY_FILE="usb.overlay" \
#     -DCONFIG_MCUMGR_GRP_OS_MCUMGR_PARAMS=y


west build -b nrf52840dongle/nrf52840/bare \
    samples/subsys/mgmt/mcumgr/smp_svr \
    --sysbuild --domain smp_svr \
    -- \
    -DEXTRA_CONF_FILE="bt.conf;cdc.conf;fs.conf;shell-mgmt.conf" \
    -DEXTRA_DTC_OVERLAY_FILE="usb.overlay" \
    -DCONFIG_RTC=y \
    -DCONFIG_THREAD_MONITOR=y \
    -DCONFIG_THREAD_RUNTIME_STATS=y \
    -DCONFIG_SCHED_THREAD_USAGE=y \
    -DCONFIG_MCUMGR_TRANSPORT_SHELL=n \
    -DCONFIG_FILE_SYSTEM_SHELL=y \
    -DCONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=4096 \
    -DCONFIG_MCUMGR_TRANSPORT_WORKQUEUE_STACK_SIZE=8192 \
    -DCONFIG_MCUMGR_GRP_OS_MCUMGR_PARAMS=y \
    -DCONFIG_MCUMGR_GRP_OS_INFO=y \
    -DCONFIG_MCUMGR_GRP_OS_TASKSTAT=y \
    -DCONFIG_MCUMGR_GRP_OS_TASKSTAT_STACK_INFO=y \
    -DCONFIG_MCUMGR_GRP_OS_BOOTLOADER_INFO=y \
    -DCONFIG_MCUMGR_GRP_OS_DATETIME=y \
    -DCONFIG_MCUMGR_GRP_OS_DATETIME_MS=y \
    -DCONFIG_MCUMGR_GRP_OS_INFO_BUILD_DATE_TIME=y \
    -DCONFIG_MCUMGR_GRP_OS_MPSTAT=y \
    -DCONFIG_SYS_HEAP_RUNTIME_STATS=y \
    -DCONFIG_SYS_HEAP_ARRAY_SIZE=32 \
    -DCONFIG_IMG_ENABLE_IMAGE_CHECK=y \
    -DCONFIG_IMG_ERASE_PROGRESSIVELY=y \
    -DCONFIG_MCUMGR_GRP_IMG=y \
    -DCONFIG_MCUMGR_GRP_IMG_FRUGAL_LIST=y \
    -DCONFIG_MCUMGR_GRP_IMG_VERBOSE_ERR=y \
    -DCONFIG_MCUMGR_GRP_IMG_SLOT_INFO=y \
    -DCONFIG_MCUMGR_GRP_FS_CHECKSUM_HASH=y \
    -DCONFIG_MCUMGR_GRP_FS_HASH_SHA256=y \
    -DCONFIG_MCUMGR_GRP_FS_CHECKSUM_HASH_SUPPORTED_CMD=y \
    -DCONFIG_MCUMGR_GRP_ZBASIC=y \
    -DCONFIG_MCUMGR_GRP_ZBASIC_STORAGE_ERASE=y \
    -DCONFIG_MCUMGR_GRP_ENUM=y \
    -DCONFIG_MCUMGR_GRP_ENUM_DETAILS=y \
    -DCONFIG_MCUMGR_GRP_ENUM_DETAILS_NAME=y \
    -DCONFIG_SETTINGS=y \
    -DCONFIG_SETTINGS_RUNTIME=y \
    '-DCONFIG_SETTINGS_FILE_PATH="/lfs1/settings"' \
    -DCONFIG_MCUMGR_GRP_SETTINGS=y \
    -DCONFIG_LOG=y \
    -DCONFIG_LOG_BACKEND_UART=n \
    -DCONFIG_SHELL=y \
    -DCONFIG_SHELL_LOG_BACKEND=y \
    -DCONFIG_SHELL_BACKEND_SERIAL=y \
    -DCONFIG_LOG_BUFFER_SIZE=16384 \
    -DCONFIG_SHELL_BACKEND_SERIAL_LOG_MESSAGE_QUEUE_SIZE=16384
